/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp2_bddm;

import java.awt.Color;
import java.awt.List;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.imageio.ImageIO;

/**
 *
 * @author TT
 */
public class NewJFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public NewJFrame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButton1)
                .addGap(49, 49, 49)
                .addComponent(jButton2)
                .addContainerGap(865, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(460, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       foo();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        foo2();
    }//GEN-LAST:event_jButton2ActionPerformed

    
    public void foo()
    {
        
        
        ArrayList<Integer> ls = new ArrayList<Integer>();
            
        try {
            BufferedImage bimg;
            bimg = ImageIO.read(new File("D:\\0Blackk.png"));
            int w = bimg.getWidth(null);
            int h = bimg.getHeight(null);
            
            int[] g = new int[256];
            
            for(int x = 0 ; x < w; x++)
            {
                for(int y = 0 ; y < h ; y++)
                {
                    int rgb = bimg.getRGB(x, y);
                    Color c  = new Color(rgb);
                    int Y = c.getRed();
                    ls.add(Y);
                }
            }
            
            int pmax = Collections.max(ls);
            int pmin = Collections.min(ls);
            
            
       
            
            for(int x = 0 ; x < w; x++)
            {
                for(int y = 0 ; y < h ; y++)
                {
                    int rgb = bimg.getRGB(x, y);
                    Color c  = new Color(rgb);
                    int Y = c.getRed();
                    
                   // System.out.print(Y + "\t");
                    Y = (Y - pmin) * 255 / (pmax - pmin);
                   // System.out.println(Y);
                    
                    Color t = new Color(Y,Y,Y);
                    int rgbNew = t.getRGB();
                    bimg.setRGB(x, y, rgbNew);
                }
            }
            
            ImageIO.write(bimg, "png",  new File("D:\\0Black2.png"));
            
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     public void foo2()
    {
        
        
        ArrayList<Integer> lr = new ArrayList<Integer>();
        ArrayList<Integer> lg = new ArrayList<Integer>();
        ArrayList<Integer> lb = new ArrayList<Integer>();
            
        try {
            BufferedImage bimg;
            bimg = ImageIO.read(new File("D:\\dark_2.jpg"));
            int w = bimg.getWidth(null);
            int h = bimg.getHeight(null);
            
            //int[] g = new int[256];
            
            for(int x = 0 ; x < w; x++)
            {
                for(int y = 0 ; y < h ; y++)
                {
                    int rgb = bimg.getRGB(x, y);
                    Color c  = new Color(rgb);
                    int r = c.getRed();
                    int g = c.getGreen();
                    int b = c.getBlue();
                    lr.add(r);
                    lg.add(g);
                    lb.add(b);
                }
            }
            
            int rmax = Collections.max(lr);
            int rmin = Collections.min(lr);
            
            
            int gmax = Collections.max(lg);
            int gmin = Collections.min(lg);
            
            
            int bmax = Collections.max(lb);
            int bmin = Collections.min(lb);
            
            
            for(int x = 0 ; x < w; x++)
            {
                for(int y = 0 ; y < h ; y++)
                {
                    int rgb = bimg.getRGB(x, y);
                    Color c  = new Color(rgb);
                    int R = c.getRed();
                    int G = c.getGreen();
                    int B = c.getBlue();
                    
                   // System.out.print(Y + "\t");
                    R = (R - rmin) * 255 / (rmax - rmin);
                    G = (G - gmin) * 255 / (gmax - gmin);
                    B = (B - bmin) * 255 / (bmax - bmin);
                    
                   // System.out.println(Y);
                    
                    Color t = new Color(R,G,B);
                    int rgbNew = t.getRGB();
                    bimg.setRGB(x, y, rgbNew);
                }
            }
            
            ImageIO.write(bimg, "png",  new File("D:\\0Black22.png"));
            
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
